### ISSUE TITLE
State pages: tables for other data tabs

### ISSUE THREAD

**Issue by lizdewolf** [Hyperobjekt/covid-19-behind-bars#109]
Adding tables for each of the other data sections (releases, grassroots, etc) on state pages. Liz will walk Josh through the plan.

**Comment by laurendoone** [comment]
@hoshmn is this task completed/on staging?

**Comment by hoshmn** [comment]
@laurendoone it's on staging, waiting for @lizdewolf to get the go-ahead from the relevant teams to merge (ideally after fixing the permalinks and dates in the source sheets)
