### ISSUE TITLE
Updating how we show rates > 100% 

### ISSUE THREAD

**Issue by erika-tyagi** [Hyperobjekt/covid-19-behind-bars#118]
Thanks for flagging the crazy high rates yesterday! (e.g. Turner's 3400% cumulative case rate) 

If it's not too much trouble on your end, we think the simplest solution for now is just to replace ALL rates above 100% with ">100%" (like how we're showing "<1%" for rates below 1%). 

* This is probably only going to be an issue for cumulative case rate, but clamping all rates (i.e. active case rate and death rates) might be safe incase there's a spike at a facility with a small population. 
* This would be on both the homepage and the state pages. 
* I'll check with Liz on whether we would want to update the footnote about rates or our methodology, but we should be able to take care of this on our own. 

Of course, let us know of any questions or issues - or if this would be complicated to implement on your end!

**Comment by james-minton** [comment]
Cap at >100%, no asterisk. Liz will send updated note for bottom of table.

Test rate also needs a % added to each figure.
