### ISSUE TITLE
Scorecard

### ISSUE THREAD

**Issue by lizdewolf** [Hyperobjekt/covid-19-behind-bars#133]
We are making some progress on the "scorecard" piece we mentioned in our meeting this week, and I thought it might be good to plan ahead a bit in terms of how it would fit onto state pages and if there are specific layout/design things we should already be thinking of. Below is a screenshot of a very basic example of what we'd include, but we will figure out some ways for it not to be so wide (however we might add some columns). We'll be adding some kind of points scoring system to this too. Not the most urgent thing but wanted to put on your radar in case it makes sense to start planning.
The info we want to get across is: is this jurisdiction reporting this variable, and if so, at the state or facility level?

https://docs.google.com/spreadsheets/d/1fHhRAjwYGVmgoHLUENvcYffHDjEQnpp7Rwt9tLeX_Xk/edit#gid=0

**Comment by laurendoone** [comment]
Team's initial thoughts:
- placing this in the bottom table area of States pages
- consolidating/abbreviating column names as needed
- progressive disclosure

To discuss:
- how much additional content do we anticipate?
- how frequently will additional content be added?

**Comment by lizdewolf** [comment]
Hi! We just had a great meeting about this. We don't anticipate a ton of changes beyond the columns in blue in [this sheet](https://docs.google.com/spreadsheets/d/1fHhRAjwYGVmgoHLUENvcYffHDjEQnpp7Rwt9tLeX_Xk/edit#gid=0).

**Comment by laurendoone** [comment]
![CBB - Scorecard 7](https://user-images.githubusercontent.com/76966798/109562182-e9210000-7a92-11eb-8c31-d1031b853ce1.png)

**Comment by laurendoone** [comment]
@hoshmn this is ready for development, with the following design feedback (we can wait for @sashasashasasha to weigh in on some of these next week if needed):

- Add the text “None” next to to the orange X’s 
- Add a legend for icons and colors - probably need @sashasashasasha for this one
- X and checks could be thicker so color stands out more
- we are considering whether we want the "data quality" row to potentially be on the bottom - not sure if that causes any design issues. we might also remove one of the metrics

**Comment by lizdewolf** [comment]
@laurendoone and @hoshmn  - can we add a word next to every X and check? So on the top row, it would be "yes" and "no", and on the bottom rows, it's "facility-level" "statewide" and "none"?

The "r" in Data Reporting for staff should also be lowercase, but that's a tiny copy thing. "machine-readable" should also be hyphenated, that was our bad. Thank you!

**Comment by lizdewolf** [comment]
@laurendoone a couple new things were raised at our staff meeting today:

1. For a few states, can we add an asterisk next to the letter grade and have a little note somewhere? we are thinking there is a metric that we want to remove from the scorecard but would still like to include some text about the issue. We basically want to note when a state has sketchy reporting behavior in the past. 

2. Can we also add "As of x date" somewhere near the scorecard? Draft copy is: "Scores assessed as of x date. Scores will be reevaluated on a quarterly basis."

**Comment by laurendoone** [comment]
@lizdewolf is there a final decision on whether "data quality" row should be on the bottom? and whether any of the metrics will be removed?

**Comment by lizdewolf** [comment]
@laurendoone thanks for checking! We just removed a couple of metrics. Final metrics here: https://docs.google.com/spreadsheets/d/1fHhRAjwYGVmgoHLUENvcYffHDjEQnpp7Rwt9tLeX_Xk/edit#gid=0

Since data quality now has only three metrics, we are thinking it might look best to have the rows in the following order:

Data reporting for incarcerated people
Data reporting for staff
Data quality

**Comment by laurendoone** [comment]
@sashasashasasha for design mockup:

- [ ] Add a legend for icons and colors 
- [ ] X and checks could be thicker so color stands out more
- [ ] For a few states, can we add an asterisk next to the letter grade and have a little note somewhere? we are thinking there is a metric that we want to remove from the scorecard but would still like to include some text about the issue. We basically want to note when a state has sketchy reporting behavior in the past.
- [ ] Can we also add some copy that says the date near the scorecard? Draft copy is: "Scores assessed as of x date. Scores will be reevaluated on a quarterly basis."
