### ISSUE TITLE
Separate Methods and FAQ pages

### ISSUE THREAD

**Issue by laurendoone** [Hyperobjekt/covid-19-behind-bars#137]
Break out Methods page separate from FAQ. I think it may make more sense to do this along with https://github.com/Hyperobjekt/covid-19-behind-bars/issues/141 since they are somewhat dependent on each other?

**Comment by lizdewolf** [comment]
@laurendoone we no longer need to do the graphics on the methods page. we met this afternoon and changed our approach. however, if, when we change the menu, we can just cut and paste the text from methods and FAQ to two separate pages (for ease of navigation), that would be great. No design needed for now.

**Comment by laurendoone** [comment]
Noted! Will prioritize this above the menu task.
