### ISSUE TITLE
Footer: add new pages to footer

### ISSUE THREAD

**Issue by laurendoone** [Hyperobjekt/covid-19-behind-bars#139]
Feedback from Sasha: Now that there are multiple new pages being added they could be linked to in the footer in a structured way (something like the screenshot attached):

TO DO:
- When new pages are created/added, add to footer
- Add "State & Federal" data to the "Data" section of the footer (in screenshot below) - where does this link to though? homepage?

![image](https://user-images.githubusercontent.com/76966798/106339100-73830380-624a-11eb-9ff3-427df1c3d3fd.png)

Still need to determine priority

**Comment by hoshmn** [comment]
I know this isn't top prio, but when it is @sashasashasasha it'd be helpful to see this on mobile (gonna be a long list 🙂) and tablet if possible. I'm also not sure about Lauren's question, where should a State link go to... not sure there's a better option than Home, where they hopefully then understand they can click a state. Alternatively there could be a select-a-state dropdown in the footer, but that might not be pretty.
