### ISSUE TITLE
Homepage map updates

### ISSUE THREAD

**Issue by laurendoone** [Hyperobjekt/covid-19-behind-bars#140]
See James' updates in comment below!

**Comment by james-minton** [comment]
Updates on tasks for this before moving to live site:

- [ ] Need to implement new colors/design for spikes as agreed to in channel
- [ ] At 1280+, could we change the map section layout [to what is shown here](https://www.figma.com/file/mpEe8LcUU1nTpFM1TkK8TN/UCLA-CBB-DRAFT?node-id=756%3A1487)? Image attached as well.
![CBB - Homepage update 1](https://user-images.githubusercontent.com/33635008/106392265-05ac1880-63bf-11eb-9fcd-34084b453435.png)

**Comment by laurendoone** [comment]
![Uploading image.png…]()

**Comment by sashasashasasha** [comment]
@james-minton Changing the width of the map is only part of the solution of increasing container width throughout. Increasing the width of the container for the entire site would remove the horizontal scroll bar from the homepage table, help with the overlapping on the state page and help fit the content of all the state tables.

Also this layout change would help not only at 1280+ but also the breakpoint between ipad and 1280px.

![CBB breakpoint](https://user-images.githubusercontent.com/12460782/106900053-f6dea200-66ed-11eb-9f79-cc81ed87e1f9.png)
![CBB table 2](https://user-images.githubusercontent.com/12460782/106900059-f80fcf00-66ed-11eb-93e6-01910565dc8c.png)
![CBB table 3](https://user-images.githubusercontent.com/12460782/106900060-f80fcf00-66ed-11eb-8c20-3bd1b5ef29a5.png)

**Comment by laurendoone** [comment]
Final feedback from Sasha/James:

- [ ] see annotations in attached image and see figma file for details 
![4791DA5B-2B33-4FF6-92A5-F028654EC0A9](https://user-images.githubusercontent.com/76966798/106923637-262be980-66c3-11eb-9afe-bb9709e82be2.jpeg)

https://www.figma.com/file/TKdSksUXJjYDl9FePrEiZz/UCLA-CBB-Style-guide-Site-map?node-id=285%3A0

- [ ] Also in general I really do not want spikes colliding with text elements. It looks bad (see image 1 below at a below-1280 breakpoint). An acceptable low-tech fix to my mind would be adding a background-color to that box (2nd image) that matches the overall background color. It will cut off the tip of that one spike but I'd prefer that to it jutting into and competing with the text.

**Comment by hoshmn** [comment]
@sashasashasasha it's a valid point that there is more layout width that we could be using across the site, but I'm not seeing any details about that in the ticket. Seeing the added link to the figma mockup of a homepage without the current margin -- is that just for 1280+, or you're saying also for the breakpoint below that? And in terms of how this benefits other pages, I guess that suggests I should apply the same margin/content width changes across the board? Again, I do see the possible benefit, just want to be clear on what's entailed here (and if there's fallout/cleanup to be done from increasing the content width everywhere this may be more work than the homepage map updates I took it to be).

**Comment by sashasashasasha** [comment]
@hoshmn Good point yes, maybe this should be a separate ticket. If this increase is applied to the homepage now it can be applied to other pages too. The homepage, state page and blog are the only ones that have been designed and implemented so far. The other live pages are placeholders so far. 

This would help the breakpoint between ipad and 1280px too. I attached a mockup at 1150px in the [same Figma file.](https://www.figma.com/file/TKdSksUXJjYDl9FePrEiZz/UCLA-CBB-Style-guide-Site-map?node-id=992%3A0)

**Comment by laurendoone** [comment]
@sashasashasasha @hoshmn created separate ticket for this and assigned a low priority for now https://github.com/Hyperobjekt/covid-19-behind-bars/issues/154
