### ISSUE TITLE
Reorganize menu + footer

### ISSUE THREAD

**Issue by laurendoone** [Hyperobjekt/covid-19-behind-bars#141]
Update menu according to the following: https://docs.google.com/document/d/17LOnXfe6CwLrC0V-Mygf0bODfx6kVQWHEfYsOmeKswA/edit

To do:
- [ ] Separate Methods & FAQ pages
- [ ] Separate "In the News" from About page and make it its own page
- [ ] Separate "Opportunities" from About page and make it its own page

**Comment by laurendoone** [comment]
@sashasashasasha can you review if what I listed above is correct before Josh begins development on this? I'm still a little unclear on how the Explore Data section works in the header and what is top level vs. sub-items, etc

**Comment by hoshmn** [comment]
Yeah, it looked from Slack like this is still in design. I've done some of the groundwork but will put on hold and look at the immigration page. @sashasashasasha It would be good to see a mockup for the mobile menu as well, unless it should just be as it is now, but with dropdowns for the new submenu sections.

**Comment by hoshmn** [comment]
@laurendoone FWIW I will probably come back to this when both it and the footer are ready, because there are some interdependencies between them in the code.

**Comment by laurendoone** [comment]
Putting in blocked status until we get updated designs for menu and footer (mobile & desktop)

**Comment by ekmason** [comment]
From Liz: Footer archive link is https://us7.campaign-archive.com/home/?u=5d704f1af2db3979886a8cde2&id=fa6a9cea7f

**Comment by hoshmn** [comment]
> From Liz: Footer archive link is https://us7.campaign-archive.com/home/?u=5d704f1af2db3979886a8cde2&id=fa6a9cea7f

@ekmason thanks! Couple of questions: 
- we’re just going to link to that external Mailchimp URL in the footer, right? (I think the instructions on the other ticket had to do with embedding the archive, to render them within your own site, but seems like Liz was fine with taking the simpler route that the Marshall Project took)
- should it just be listed as Newsletter Archive, as the last item (or above contact?)? 
- I assume if the archive page is going to have a logo/branding at the top that gets configured within Mailchimp

**Comment by ekmason** [comment]
> we’re just going to link to that external Mailchimp URL in the footer, right?

Yes, we're going with the simpler approach! No need for any styling at all, we'll just link to that page she has provided. 


> should it just be listed as Newsletter Archive, as the last item (or above contact?)?

I think Sasha must have updated the figma file, but this archive link should be just under the newsletter subscription (pictured below)

<img width="709" alt="Screen Shot 2021-04-09 at 7 02 05 PM" src="https://user-images.githubusercontent.com/80919000/114248784-a0e4df80-9966-11eb-8a4c-e23db529df9b.png">


> I assume if the archive page is going to have a logo/branding at the top that gets configured within Mailchimp

Yes, that would have to be configured in Mailchimp. Liz decided to set up on the UCLA end, so we no longer control that page, we're just linking to it :)

**Comment by hoshmn** [comment]
Perfect, thanks!

**Comment by sashasashasasha** [comment]
Desktop

- Add dropshadow to top nav: 0px 5px 10px rgba(0, 0, 0, 0.05); 
- Make the dropshadow for _publication&resources_ and _about_  0px 5px 10px rgba(0, 0, 0, 0.04);
- Can we replace the dashed line which splits the top nav from the dropdown with a solid line, colour #F1F1EB
- Larger spacing at the top and bottom of the data dropdown menu. 30px at the top and 40px at the bottom. I have added orange squares to show this spacing in the [Figma mockup](https://www.figma.com/file/TKdSksUXJjYDl9FePrEiZz/UCLA-CBB-Style-guide-Site-map?node-id=1323%3A0).
- Within 'Explore data' dropdown the dividers should be less prominent - colour #C8C8B9.
The words ‘By federal agency’ and ‘By state’ should be less prominent with colour #555526.

Mobile
- Make slide out menu full width to avoid repeating the logo. 
- Add 'close' next to cross.
- Replace menu icon with one that has 'menu' included. I have added this to [Figma](https://www.figma.com/file/TKdSksUXJjYDl9FePrEiZz/UCLA-CBB-Style-guide-Site-map?node-id=1431%3A27).

**Comment by hoshmn** [comment]
@sashasashasasha thanks for the feedback! I'll try to implement tomorrow. Regarding the mobile menu, though: it converts to this version of the menu at 1022px (desktop menu needs to be wide to accommodate all the states), so I'm not sure we want it to be full width (see screenshot below).
<img width="1178" alt="Screen Shot 2021-04-13 at 8 39 52 PM" src="https://user-images.githubusercontent.com/18331999/114638002-a6109a00-9c98-11eb-8313-431c336e32d9.png">

Also, for the "close" and "menu" text, the icon itself is what will get the background on hover (see below). I guess the text would be part of the button that responds to the click event, but wouldn't be styled on hover?
<img width="80" alt="Screen Shot 2021-04-13 at 6 35 47 PM" src="https://user-images.githubusercontent.com/18331999/114638181-07d10400-9c99-11eb-8612-16542de6119a.png">

**Comment by hoshmn** [comment]
@sashasashasasha waiting to confirm those mobile questions, but the rest is updated [here](https://6077409b7310100008310772--covid-19-behind-bars.netlify.app/)

**Comment by sashasashasasha** [comment]
@hoshmn its looking really good so far!

The menu looks great not being full width on an ipad. What about making it full width only on mobile? 

Also on an iphone there is currently a slight zooming in once a state is selected from the state dropdown.As soon as the state dropdown is clicked the view is zoomed in and then the menu icon disappears from the top right corner. I can try create a video of this. 

For the "close" and "menu" the text can be part of the button and on hover there can be a slight background colour change. I have added mockups in [Figma] to show this (https://www.figma.com/file/TKdSksUXJjYDl9FePrEiZz/UCLA-CBB-Style-guide-Site-map?node-id=1278%3A38)

![CBB - nav mobile hover - close](https://user-images.githubusercontent.com/12460782/114862012-40f99900-9dab-11eb-819a-97fbffbc76e6.png)
![CBB - nav mobile hover - menu](https://user-images.githubusercontent.com/12460782/114862015-422ac600-9dab-11eb-9315-3fe3219aa46a.png)

**Comment by ekmason** [comment]
@hoshmn I just wanted to add details from Liz on the report to be included in the Resources & Reports page: 

The report to be included is the JAMA report which is currently on the Media page (see screenshot). 

In light of this, can we make the following changes?
- [ ] Add a Reports section at the bottom of the new Reports & Resources page, with the single JAMA report
- [ ] Change page name to Resources & Reports since the resources section comes first on the page

![image.png](https://images.zenhubusercontent.com/605b8464e0e66f4aa2b43f51/7fe3a7bb-85ae-4637-b629-6193c98b99f2)

**Comment by hoshmn** [comment]
Pushed [updates](https://6078b685f130660007664286--covid-19-behind-bars.netlify.app/resources)

@ekmason sorry I didn't respond to the Slack message about that! Good catch. I moved it over but haven't done anything to unify the styles. Might need copy for a blurb to follow the report link for it to work here? Worth considering what the Reports page will look like when it gets created (more of a bare list like the Media page or with descriptions like the Resources).
![Screen Shot 2021-04-15 at 7 21 00 PM](https://user-images.githubusercontent.com/18331999/114949882-f5cd9d80-9e1f-11eb-8b48-02aef697d06d.png)

@sashasashasasha I updated the Menu/Close icons. Menu is full-page for mobile. Also for mobile, I bumped the dropdown menu and other page links up 2px to 16px -- that fixes the zooming thing on iPhone (which happens because it detects the text is small and "helpfully" zooms in so you can more easily read it).

**Comment by ekmason** [comment]
@hoshmn Excellent point on the styling... for now I'm thinking we can do the following 

COVID-19 Cases and Deaths in Federal and State Prisons ---> this will be the title/header for the report (orange)
JAMA report --> this will be the description for now... once they build out a reports page, we can revisit the copy/styling for this.
