### ISSUE TITLE
Consult on new hex maps for social media

### ISSUE THREAD

**Issue by laurendoone** [Hyperobjekt/covid-19-behind-bars#142]
Request from Liz: we were thinking about making a set of those same hex maps for issues related to policies and practices by state as well, but were thinking it would make sense to use a different color palette than the other data maps, so they don't all look the same. could you recommend a three-color palette to use? we can re-use some of the colors from our graphs, whatever you think makes sense

of course this is not high priority, will be making these towards the end of next week.

**Comment by sashasashasasha** [comment]
Liz added:

- we'll use it on the blog and on socials
- yet another potential update -- we would love to add two hexes off to the side on each post that stands for ICE (immigration detention) and for BOP (federal prisons). Potentially a slightly bigger hex than the state ones. What do you think about that? I can make a mock up of what I had in mind

**Comment by laurendoone** [comment]
@sashasashasasha Liz will also share some new hex maps for your feedback (via slack)

**Comment by lizdewolf** [comment]
@laurendoone this one is wrapped! thank you @sashasashasasha
