### ISSUE TITLE
Increase width of the container for the entire site

### ISSUE THREAD

**Issue by laurendoone** [Hyperobjekt/covid-19-behind-bars#154]
Feedback from Sasha: increase the width of the container for the entire site - helps to remove the horizontal scroll bar from the homepage table, help with the overlapping on the state page and help fit the content of all the state tables.

Also this layout change would help not only at 1280+ but also the breakpoint between ipad and 1280px.

If this increase is applied to the homepage now it can be applied to other pages too. The homepage, state page and blog are the only ones that have been designed and implemented so far. The other live pages are only placeholders.

This would help the breakpoint between ipad and 1280px too. I attached a mockup at 1150px in the same Figma file.

![image](https://user-images.githubusercontent.com/76966798/106936272-3cd93d00-66d1-11eb-81a5-f94be9171061.png)
![image](https://user-images.githubusercontent.com/76966798/106936292-42cf1e00-66d1-11eb-8409-c197ab3515e4.png)
![image](https://user-images.githubusercontent.com/76966798/106936306-4662a500-66d1-11eb-9a64-6c5f966bb936.png)

**Comment by laurendoone** [comment]
Moving this to high priority since the scorecard https://github.com/Hyperobjekt/covid-19-behind-bars/issues/133 is dependent on this

**Comment by hoshmn** [comment]
I take it [this](https://www.figma.com/file/TKdSksUXJjYDl9FePrEiZz/UCLA---CBB---Style-guide%2C-Site-map?node-id=285%3A0) is the figma file. I imagine we'll still want some max-width value for the content, no? The point at which the page elements no longer benefit from the additional width and they even maybe become awkward or clownish.

**Comment by laurendoone** [comment]
@hoshmn yep that's the correct figma file! regarding max-width, here's the latest from Slack (Feb 4):

James: Sure, what should the max-width for the container be, then? 

Sasha Zyryaev: For recent 1280px mockups I have been using 12 columns at 70px each with 30px gutter which gives a max-width of 1170px. It can be a similar number thats easy to implement as long as its over 90% of the width and leaves a little space on the sides.

**Comment by hoshmn** [comment]
For 1280+ the max-width is 1280px, so 1170px would be _reducing_ the max-width. Content in the md breakpoint (960px - 1280px) currently gets a max-width of 960px, so I could just remove that.

**Comment by laurendoone** [comment]
@sashasashasasha can you take a look at the update on internal staging and provide feedback if any? https://internal-staging--covid-19-behind-bars.netlify.app/states/maryland/

**Comment by sashasashasasha** [comment]
For 1280+ the max-width can be larger. What would be easy to implement for 1280+?

The legend for the map is being cut off at the bottom on a laptop 
![Container width Screenshot 1](https://user-images.githubusercontent.com/12460782/110332870-8d9cc800-7fe6-11eb-8e39-ba6b0bb6f2b5.png)

The width seems to be different between different sections on the page
![Container width Screenshot 2](https://user-images.githubusercontent.com/12460782/110332887-91304f00-7fe6-11eb-8f5e-ecc665854f5b.png)
![Container width Screenshot 3](https://user-images.githubusercontent.com/12460782/110332891-92617c00-7fe6-11eb-8abd-fa33158a99cf.png)
![Container width Screenshot 4](https://user-images.githubusercontent.com/12460782/110332903-955c6c80-7fe6-11eb-8c25-affb38b68772.png)

**Comment by hoshmn** [comment]
@sashasashasasha check out internal staging and let me know if I've resolved those issues with the left alignment and legend being cut off. I also set the max content width to 1400px. And, while you're at it, check how the [blog](https://internal-staging--covid-19-behind-bars.netlify.app/blog/lorem-ipsum) looks with the 700px max width.
