### ISSUE TITLE
Homepage: add table for vaccine data

### ISSUE THREAD

**Issue by laurendoone** [Hyperobjekt/covid-19-behind-bars#166]
High level request: add a simple table on the homepage, below the current facility table, where we can list which states are reporting vaccine data by variable type. Use existing table design/styling. Data team will provide data.

**Comment by lizdewolf** [comment]
The table will pull from the [main dataset](https://github.com/uclalawcovid19behindbars/data/blob/master/latest-data/adult_facility_covid_counts.csv) and include only the variables in columns Y-AD:

- Residents.Initiated 
- Staff.Initiated
- Residents.Completed
- Staff.Completed
- Residents.Vadmin
- Staff.Vadmin

We'd like to display only those jurisdictions (rows) that have data reported in at least one cell within the above columns. Many jurisdictions are not reporting, and they won't be included in the table. As additional jurisdictions begin reporting these variables, we'd like to add them to the table. 

For the display of the table, we'd like each variable (column) to be reordered and renamed on the front-end as the following:

- Residents.Initiated --> Number of incarcerated individuals who have received any dosage
- Residents.Completed --> Number of incarcerated individuals who have completed dosage schedule
- Residents.Vadmin --> Number of vaccines administered to incarcerated people
- Staff.Initiated --> Number of staff who have received any dosage
- Staff.Completed --> Number of staff who have completed dosage schedule 
- Staff.Vadmin --> Number of vaccines administered to staff

Copy:

Title of table: COVID-19 Vaccines in Carceral Facilities
 
Table blurb:

This table reflects data we have obtained from correctional agencies about the administration of COVID-19 vaccines to incarcerated people and staff in their facilities. Agencies differ in the variables they report about vaccination. We will add jurisdictions and variables to this table as more data become available.

**Comment by hoshmn** [comment]
@lizdewolf what I'm seeing is 3 statewide rows and 10 facility rows (all in Minnesota). The idea is just to show the statewide rows, right? I also don't see the ICE row you mentioned ([line 1491 on master](https://github.com/uclalawcovid19behindbars/data/blob/master/latest-data/adult_facility_covid_counts.csv#L1491) isn't it) <img width="847" alt="Screen Shot 2021-02-22 at 12 18 39 PM" src="https://user-images.githubusercontent.com/18331999/108764995-1eb07100-7508-11eb-951e-0dee4f2be941.png">

**Comment by lizdewolf** [comment]
@hoshmn hi Josh! 

I didn't realize that states would be reporting at the facility level (which is actually great!), so I apologize I didn't specify what to do in that case. Ideally, we would aggregate all data within a state and sum it into a statewide row (in this case, only for MN). Is this possible?

For your second question, it looks like the row might have shifted, its now number 1490. The Facility.ID is 1878 for "ALL ICE FACILITIES"

**Comment by hoshmn** [comment]
Hey @lizdewolf! Whoops, sorry I didn't see it there right above 1491 🤦‍♂️ for now it looks like it doesn't have any values for the relevant fields, which is why it wasn't making it into the table, but I can have it display as "U.S. Immigration and Customs Enforcement" if it does make it into the table.

I can have facilities aggregate into a statewide value, but let's check in about this at the meeting tomorrow. We'd need to decide: if there is a statewide value as well as facilities within that state, do we ignore the facilities or aggregate them? What if the statewide row has a count for vadmin but not initiated/completed -- do we aggregate the facilities' values for those?

**Comment by lizdewolf** [comment]
Thanks, and sounds good to both!

If we are able to get data at the facility level, we don't also scrape statewide, so the situation shouldn't arise where we have to choose.

**Comment by laurendoone** [comment]
@hoshmn feedback from tuesday meeting:
- [ ] Disable filtering for the vaccine table (so the map filtering does not control this table's filtering)

**Comment by lizdewolf** [comment]
@hoshmn @laurendoone we can use these column headers for the table:
https://docs.google.com/spreadsheets/d/1FQZ1EYGdy8VjnsnMxux_0iQsa0LYjCnG-lDhGvIML4g/edit#gid=0

**Comment by lizdewolf** [comment]
@hoshmn also, we now have data for BOP vaccines. similar to the ICE line, it has "ALL BOP FACILITIES" in a different column on row 1713. Can we add that one and have it say "Federal Bureau of Prisons" for jurisdiction? Thank you!

**Comment by lizdewolf** [comment]
@laurendoone and @hoshmn the data team came up with a way to simplify further. we will be merging variables into "vaccines administered to incarcerated people" and "vaccines administered to staff". we'll be merging them on our own github so you can pull directly. Will let you know asap when this is done. Will have a couple of notes to add under the table, copy forthcoming.

**Comment by lizdewolf** [comment]
@hoshmn @laurendoone the data is ready! You can pull from this sheet: https://github.com/uclalawcovid19behindbars/data/blob/master/latest-data/state_aggregate_counts.csv and just pull from Residents.Vadmin and Staff.Vadmin.

The column headers should read:

Residents.Vadmin -- Vaccines administered to incarcerated people
Staff.Vadmin -- Vaccines administered to staff

**Comment by laurendoone** [comment]
@hoshmn updates from tuesday check-in:
- [ ] Add copy below table with link to Methods page (@lizdewolf to provide copy)
- [ ] Federal Bureau of Prisons row - link to federal data
- [ ] Once the above are done, push to staging environment

**Comment by lizdewolf** [comment]
Hi @hoshmn rather than add a line of copy below the table, I think we can just replace the current paragraph blurb with this:

This table reflects data publicly reported by correctional agencies about the administration of COVID-19 vaccines to incarcerated people and staff in their facilities. Agencies differ in the number and definitions of variables they report about vaccination, but, to the best of our knowledge, the numbers reported below refer to the number of people who have received at least one dose of a vaccine. Some individuals may have also received a second dose, though it is not always clear from the data. We will add jurisdictions and variables to this table as more data become available.

**Comment by lizdewolf** [comment]
@hoshmn @laurendoone  I'm also wondering if we can add a row that is just a total for each column, and also whether we can right-justify the name of the jurisdiction in the column, so it's closer to the numbers and a bit easier to read.

**Comment by laurendoone** [comment]
@lizdewolf 
1) I'm also wondering if we can add a row that is just a total for each column - are you thinking like a "total" row at the top or bottom of the table that sums each column?
2) we can play around with the justification to see what looks best

**Comment by laurendoone** [comment]
@hoshmn feedback on the vaccine table from client UAT:
- [ ] Total row - move to the top of the table instead of the bottom
- [ ] Copy change: please change the last sentence to "We will add jurisdictions to this table as more data become available."
- [ ] reduce the max width another 100px (to 760px)

**Comment by laurendoone** [comment]
@hoshmn client approved, ready for production release
