### ISSUE TITLE
Information Architecture

### ISSUE THREAD

**Issue by Lane** [Hyperobjekt/covid-19-behind-bars#2]
# Summary

The information architecture for the website will give the team a common understanding of who the site is being built for and why content is structured the way it is.

# Deliverable

As a starting point, documentation around the following would be helpful:

- **User Personas / Stories**
  - describe the primary users of the site
  - what are their goals and what do they want to be able to do on the site
  - what do they struggle with, given the data / sites that are available today?
- **Content Inventory**
  - summarize the content that will be available on the site
- **Navigation Hierarchy / Site Map**
  - site map diagram, shows how content from the **content inventory** is organized into pages
  - user flow diagram / simple wireframes showing how the structure supports the goals outlined in the **user personas / stories**

**Comment by Lane** [comment]
# What's left to do

- Finish [site map](https://www.figma.com/file/TKdSksUXJjYDl9FePrEiZz/UCLA-CBB-Style-guide-Site-map?node-id=26%3A2) for mvp
- Post user persona template on slack, have UCLA team fill out one or two based on their research
- Determine navigation structure for site map
  - what are the top level navigation items
  - will there be submenus?
  - how will users navigate to federal page? (top level nav?)
  - how will users navigate to state pages? (search + homepage selection?)

**Comment by james-minton** [comment]
### Site map 

Monday, Nov 9

- Home/map with prison/jail data – (from here, people can access state and federal pages for more detail)
- Header
- Intro text
- Map
- Text
- Sponsors
- Mailing list signup
- Set up MC account
- Footer

- States pages
- there would still be simple information about immigration and grassroots on the state pages, only if geographically relevant. The desire for separate pages for each of those comes from specific interests around visualization/analysis at a national level that wouldn't work as a view on the main homepage map

- Federal Page

- About us (includes supporters and partners)
- Sponsors
- Contributors
- Media and publications (includes media coverage and our own publications – could split)
- Other resources (can link out to other organizations)
- Methods and FAQ
- Contact form
- User survey
- Survey Monkey or Qualtrics

**Non MVP**
- Immigration detention (separate map on new page) Non-MVP
- Grassroots organizing efforts (separate map on new page) Non-MVP
- Stories (qualitative/testimony) Non-MVP

**Comment by Lane** [comment]
User personas will continue to come in, separate tasks for individual page content.  Site map set above.
