### ISSUE TITLE
Time Series Chart Component

### ISSUE THREAD

**Issue by Lane** [Hyperobjekt/covid-19-behind-bars#20]
## Description

This ticket outlines all work remaining on the Time Series component before release. 

## Requested Changes

**Chart View**
- Add jurisdiction (web group) indicator to all chart related tooltips
- Exclude death rate data (included in filtered IDs?) 
     - different use case b/c variable is being filtered out
     -  for now, show all variables except death rate data. UCLA will request additional variable filtering if needed. 
- Update source data
     - [Old source](http://104.131.72.50:3838/scraper_data/summary_data/scraped_time_series.csv)
     - New source is split into two files: 
          - [Statewide](https://github.com/uclalawcovid19behindbars/data/blob/master/historical-data/historical_state_counts.csv) time series data
          - [Facility-level](https://github.com/uclalawcovid19behindbars/data/blob/master/historical-data/historical_facility_counts.csv) time series data
     - All column names, etc. should remain the same (only source link changes)
- Update data notes that display missing data warnings to use sentence case, update verb conjugation to treat "data" as a plural noun
     - Current example: "Active Cases data for Incarcerated People is not available for All ICE Facilities."
     - Update to: "Active cases data for incarcerated people **are** not available for all ICE facilities."
- Add data notes functionality 
- Add "View our data on Github" [(source link)](https://github.com/uclalawcovid19behindbars/data/tree/master/historical-data)

![image.png](https://images.zenhubusercontent.com/605b8464e0e66f4aa2b43f51/fc6b7f04-1e59-403e-892a-8aa3b38c0c49)

**Selection Modal**
- Use filtered ID list to filter out facilities whose data will not be visible in the chart
     - FilteredID list: [exclude_dashboard_facilities.csv](https://github.com/uclalawcovid19behindbars/covid19_behind_bars_scrapers/blob/master/prototyping/exclude_dashboard_facilities.csv)
     - This was shared via Slack [here](https://hyperobjekt.slack.com/archives/C017SMGMFPU/p1638208420001400)
- Add text to data selection modal that informs users that they can type to search in addition to scrolling to find the facility name ("Type to add location" instead of "Add location") 
- Add functionality to enable UCLA team to define which facilities are populated by default

![image.png](https://images.zenhubusercontent.com/605b8464e0e66f4aa2b43f51/9b498a05-88f6-4a10-8e7c-4cc1931eeddb)

## Timeline
November 29 - December 3: Implementation (Hyperobjekt)
December 6 - 10: UCLA QA of Time Series feature
December 10: HO to check in with UCLA for release approval
December 13: Tentative Release

**Comment by hoshmn** [comment]
@Lane @ekmason looks good, my main question is how to interpret the "STATEWIDE" values on the exclusion list:
<img width="298" alt="Screen Shot 2021-11-26 at 12 12 03 PM" src="https://user-images.githubusercontent.com/18331999/143626281-a08bd30e-4786-4158-bf30-9307f2a0db28.png">
my assumption is that this indicates to exclude rows with a name==="STATEWIDE" for such-and-such states from the visual, but I'm not actually seeing _any_ "STATEWIDE" values in the new source data, so wanted to be sure it's not indicating to exclude _all_ facilities within that state or something like that. Looking at the _old_ source data I do see thousands of "STATEWIDE" values, so maybe they just successfully filtered out some of the values they wanted to exclude on their end -- though then I'm also curious why the "STATEWIDE" values for states _not_ on the exclusion list are also all missing from the new data?
