### ISSUE TITLE
Homepage redesign

### ISSUE THREAD

**Issue by laurendoone** [Hyperobjekt/covid-19-behind-bars#213]
New version of the homepage to address the following issues:
- reconfigure hero area so there's not a big white blank space
- find a way to introduce the vaccine table on the homepage
- showcase recent blogs/newsletter updates/alerts
- "cards" that link to other site pages

**Comment by ekmason** [comment]
- [ ] reconfigure hero area so there's not a big white blank space
- [ ] find a way to introduce the vaccine table on the homepage
- [ ] showcase recent blogs/newsletter updates/alerts
- [ ] "cards" that link to other site pages
(Liz says this last one is covered by "recent updates").
