### ISSUE TITLE
UX improvement: add underline to state name when hovering

### ISSUE THREAD

**Issue by laurendoone** [Hyperobjekt/covid-19-behind-bars#215]
On the homepage tables, it's not obvious that you can click on a row to take you to the state page. 

Solution: 
- when hovering over the row, underline the state name (bold underline)
- keep the shaded background color as-is
- user can click on the entire row to link to the state page

**Comment by Lane** [comment]
i'm not sure if underlining the state name on hover will be a good enough
indicator that clicking will bring you to the state page here.

i was thinking only the state name would be clickable.  if we want the
whole row clickable, i think we should add a tooltip or some indicator that
clicking the row will open the state page.

**Comment by sashasashasasha** [comment]
Tooltip is a better solution!

**Comment by hoshmn** [comment]
Here's a potential implementation with just the state name being clickable. When you hover a row, the state name gets an underline to show it's a link. When you hover the state name itself, cursor becomes a pointer and the underline turns orange (the way the State pages section navigation links do).  As in this video: 

https://user-images.githubusercontent.com/18331999/110724009-de204b00-81c9-11eb-8f91-e090da145490.mov

**Comment by hoshmn** [comment]
@sashasashasasha let me know when you get the chance to review the above. For me it feels like this approach works (can tweak how the underline/color come in from hovering the row vs the state name itself), but if you prefer the tooltip approach let me know what that should look like.

**Comment by Lane** [comment]
@hoshmn yep, this looks good to me! can you open a PR with this?
