### ISSUE TITLE
Scorecard graphic for blog post

### ISSUE THREAD

**Issue by laurendoone** [Hyperobjekt/covid-19-behind-bars#223]
When we go live with the scorecard feature, the client also plans to post an associated blog post and requested a static image/graphic that could be included in the blog post. 

Requirements:
- the graphic should show all the scores for all DOCs - like here https://docs.google.com/spreadsheets/d/1MedNDtpeMw0IvXRxUNGxRTaZG0QivMW9kg_f-I_isHc/edit#gid=1334450444
- All metrics across the top, and all DOCs/states as rows
- Liz provided some examples of what they were thinking of:
![Screen Shot 2021-03-10 at 2.11.39 PM.png](https://images.zenhubusercontent.com/5ff386b68d2c76e2550af4ad/fba26b0c-6e05-4e27-8bd5-87d8ecd9ab80)
if that's too wide, we can just do symbols and cut the little text explanations next to them. it'll all be explained in the blog post, and we'll link to raw data

or 
![table-output.png](https://images.zenhubusercontent.com/5ff386b68d2c76e2550af4ad/e1989494-19fb-4024-a744-532d5695416c)

**Comment by sashasashasasha** [comment]
@laurendoone @james-minton What is the best way to proceed with this?

**Comment by laurendoone** [comment]
since we're no longer doing a static image, closing this issue
