### ISSUE TITLE
[UX] Links to scorecard in table are ambiguous

### ISSUE THREAD

**Issue by Lane** [Hyperobjekt/covid-19-behind-bars#236]
In the first table on the states pages, the data scores are letters with links that jump to the scorecard section.  There are some UX issues here:

- The down arrow could be interpreted as something related to the letter score (e.g. score has gone down)
- It is not clear that these are links, or what they will do.

![image](https://user-images.githubusercontent.com/21034/111511922-6d6ab880-870c-11eb-8020-961dd05c14c4.png)

Some design is needed here.  These should probably be text links that:

- have a visual presentation of a link (e.g. underline)
- have descriptive text about where the link will take you (e.g. view the scorecard for `{state name / federal}`)

**Comment by james-minton** [comment]
@Lane 

> Some design is needed here. These should probably be text links that:
> 
> have a visual presentation of a link (e.g. underline)
> have descriptive text about where the link will take you (e.g. view the scorecard for {state name / federal})

Agreed, the down arrow especially is misleading. Can this be fixed simply enough by adding the underline, and for the description, adding a tooltip? (Wondering if we can minimize new design and remedy this as simply as possible.)

**Comment by ekmason** [comment]
@hoshmn Liz asked for some tweaks to this work, could we make the following changes? 

- Decrease font of the tooltip (currently it looks to be about the same as the table headers?)
- Decrease margins between font and tooltip to make margins smaller
- Capitalize and update the phrase 'go to ___ scorecard' -> "View ___ scorecard"
-  Where applicable, refer to federal scorecard as BOP scorecard (so new copy would be "View BOP scorecard"/"View state scorecard"
