### ISSUE TITLE
Set fixed column widths on tables

### ISSUE THREAD

**Issue by Lane** [Hyperobjekt/covid-19-behind-bars#239]
Tables on the state page should have fixed column widths so the columns don't jump around when switching sorting

Current:
![image](http://g.recordit.co/lYrla4yrX7.gif)

Desired:

![image](http://g.recordit.co/8UpghyLOCl.gif)

**Comment by ekmason** [comment]
Liz mentioned/requested something similar [here](https://hyperobjekt.slack.com/archives/C017SMGMFPU/p1618859200000900)
