### ISSUE TITLE
Home page design review

### ISSUE THREAD

**Issue by Lane** [Hyperobjekt/covid-19-behind-bars#240]
hey @sashasashasasha (cc: @james-minton)

just want to check with a few things on the homepage design and make sure they are displaying how you've intended

## Content Widths (Header + Map)

On larger displays, 
- the header content max width is smaller than the body content max width, should this be extended so the logo aligns with the content widths? (see red lines)
- the map extends outside of the content boundaries on the right side, should we scale down this map or adjust the left margin a bit on this section so it is balanced? (see red lines)

![image](https://user-images.githubusercontent.com/21034/111524969-4ca95f80-871a-11eb-870c-1ac2bd77def0.png)

## Vaccine Table

Current view:

![image](https://user-images.githubusercontent.com/21034/111524016-2c2cd580-8719-11eb-92ab-dd9009458f07.png)

When there is space, should we be bringing the table inline with the text instead of leaving the blank space on the right?

We could use some secondary text in the column headers to cut down the column width a bit

![image](https://user-images.githubusercontent.com/21034/111523745-e1ab5900-8718-11eb-9bea-1f9e637bb6e2.png)

**Comment by sashasashasasha** [comment]
Hey @Lane,

**Content Widths (Header + Map)** 
- The header content max width should be extended so it matches the width of the content.

- I can't seem to replicate the same issue where the map is outside the right content boundary. Is this happening on the live site? 

**Vaccine Table**

Inline is better for sure. We also discussed taking out the total numbers to make them more salient. 

<img width="711" alt="Screenshot 2021-04-09 at 14 12 47" src="https://user-images.githubusercontent.com/12460782/114237728-b810d680-9940-11eb-875c-0b1b2739ec10.png">
<img width="712" alt="Screenshot 2021-04-09 at 14 14 48" src="https://user-images.githubusercontent.com/12460782/114237737-bb0bc700-9940-11eb-9d2c-3ae1a424a0e7.png">

**Comment by ekmason** [comment]
Thanks @sashasashasasha, I'll move the latter designs (highlighting totals for salience)  to a separate ticket for Phase 2. For now, we'll implement the vaccine table to be inline for now and update the content widths for header and map.
