### ISSUE TITLE
Add Puerto Rico to maps

### ISSUE THREAD

**Issue by Lane** [Hyperobjekt/covid-19-behind-bars#25]
Puerto Rico needs state page and to be added to the national map

**Comment by james-minton** [comment]
Update: 

- [ ] PR needs to be added to home page
- [ ] Is rendering as a state page (accessible via nav menu), but spikes are not rendering for cases in federal facilities?

**Comment by Lane** [comment]
@james-minton no Puerto Rico facilities have geolocation, so they don't have spikes.  Puerto Rico is added to the national map in #72
