### ISSUE TITLE
Allow home page content to be edited via CMS

### ISSUE THREAD

**Issue by Lane** [Hyperobjekt/covid-19-behind-bars#28]
Should be configured through front matter on MDX file and include the following sections

- [ ] intro
- [ ] map section / labels (e.g. title, jurisdiction names, metric names, etc.)
- [ ] table section (e.g. title, table header names, etc.)
- [ ] sponsors section (e.g. title, logos, links ,etc)

**Comment by Lane** [comment]
content has been moved to front matter, CMS config needs to be written

**Comment by james-minton** [comment]
@Lane am I correct in gathering that everything is wired up for the CMS in terms of the pages and front matter—just need to add to the config.yml file? Can take that from here, just wanting to make sure I know what stage we're in.
