### ISSUE TITLE
state map UI updates

### ISSUE THREAD

**Issue by Lane** [Hyperobjekt/covid-19-behind-bars#32]
- [x] update map based on scroll position
- [x] add map legend (indicating current metric, spike colors, sizing, title?)
- [x] add tooltip with facility readout (name and relevant stats)
- [x] highlight facility spike on table hover

**Comment by lougroshek** [comment]
@james-minton Pushed up changes for these remaining items but wondering if we want to have a slightly different appearance for table items that don't have coordinates. @Lane has noted the `useMappableFacilites` hook is available to determine that. I'm just thinking that if we're going to highlight facilities in the table when hovered there, it might be good to give users a heads-up that some facilities that have data aren't mapped so it doesn't look like a bug. Maybe we can open a new issue and circle back if it seems important?
