### ISSUE TITLE
[Spike] Determine "Get the Data" Solution

### ISSUE THREAD

**Issue by ekmason** [Hyperobjekt/covid-19-behind-bars#345]
## Context

Client would like to provide a place for users to download data in more places in the site than the Methodology page. So far the group has discussed two options: 
- Data download link at the bottom of each page showing data (homepage, state, federal, ice)
- Get the Data page, or something similar

## Deliverable
We will present determined solution to Liz for signoff before implementing. 
- [ ] Client Signoff
- [ ] Updated effort estimate
- [ ] New Ticket created to capture remaining work

**Comment by Lane** [comment]
@ekmason i'm thinking a "get the data" page would be the easiest and provide one place to get all data. we could also direct users to this page from the state pages if needed. 

estimating at 3 story points to add a simple content page with data downloads in a table similar to [SEDA data downloads](https://edopportunity.org/get-the-data/seda-archive-downloads/)

**Comment by ekmason** [comment]
@Lane - Would this require design before implementing? A few things to be finalized: 
- Page layout/design
- Copy
- Navigation: Would the Get The Data link be added to the high level site nav alongside "Explore the Data", "About", and "Publications & Resources"? 
- Copy and location of reference to data from state pages (need a full list of where on the site this page will be referenced, federal and ICE pages too?)
