### ISSUE TITLE
[Spike] Determine Internal Reports Display Solution

### ISSUE THREAD

**Issue by ekmason** [Hyperobjekt/covid-19-behind-bars#346]
## Context
Liz would like to showcase reports worked on internally (this would be research specific to their group as opposed to Reports page entries). They'd like to be able to create new standalone pages within the CMS and reference them from a page on the site. 

## Objective
Determine a solution that answers the following: 
- Where will this internal reports repository live on the site? 
- How will the client add to this repository easily? 

## Deliverable
- [x] Draft solution
- [ ] Client Signoff
- [ ] Effort Estimate
- [ ] Scope & Budget updates

**Comment by Lane** [comment]
> Where will this internal reports repository live on the site?

- add a pages collection called "Research" under the "Publications & Resources" section

> How will the client add to this repository easily?

- allow creation of pages in this section via CMS, similar to blog posts

Approximate effort: 21 story points
