### ISSUE TITLE
Blog Author Pages

### ISSUE THREAD

**Issue by ekmason** [Hyperobjekt/covid-19-behind-bars#353]
## Objective
Create a page for each blog post author where users can view all posts they've written. This should be linked to from the blog post.

**Comment by ekmason** [comment]
@Lane I'm noticing that the format is slightly different between authors. Ex. [Erika Tyagi](https://staging--covid-19-behind-bars.netlify.app/blog/authors/erika-tyagi) vs. [Liz DeWolf](https://staging--covid-19-behind-bars.netlify.app/blog/authors/liz-dewolf) - is this intentional?

**Comment by Lane** [comment]
right, there are optional "bio" and "image" fields in the CMS, in case
anyone wants a bio or image on their author page.  i put some placeholder
content in on Liz's page to show what that looks like.  if nothing is
entered on those pages, it will look like Erika's.

**Comment by ekmason** [comment]
Got it - very fancy! Love it - thanks for clarifying.
