### ISSUE TITLE
Federal Page

### ISSUE THREAD

**Issue by Lane** [Hyperobjekt/covid-19-behind-bars#44]
- [x] page that has data for federal facilities (see content doc)
- [x] add to "states & federal" navigation (mobile + desktop)

**Comment by james-minton** [comment]
Update: let's focus on a provisional version of this page for MVP launch:

>The content for the federal page is at the bottom of the content doc. Could we just include the simple info there for now?
The data sources are the same, just filtering out data by federal vs state

We could have this contained within a centered column on the page; with no map for now.

**Comment by hoshmn** [comment]
basic requirements satisfied, create new issues for refinements.
