### ISSUE TITLE
Filter "statewide" rows from tables

### ISSUE THREAD

**Issue by Lane** [Hyperobjekt/covid-19-behind-bars#45]
Some states only provide statewide counts for facilities, instead of individual facility data.  The "statewide" rows should not appear in the data tables.

**Comment by Lane** [comment]
@hoshmn still seeing this on the home page

![image](https://user-images.githubusercontent.com/21034/102543257-e3a54380-4067-11eb-8e0d-851a549c6dec.png)

**Comment by hoshmn** [comment]
@Lane whoops, first fix only touched the state pages. [fixed](https://github.com/Hyperobjekt/covid-19-behind-bars/commit/d05072ca45ceb3303209ad3e616facb6dcd0921b)
