### ISSUE TITLE
Revert Vaccine Table to Display Vaccination Rate

### ISSUE THREAD

**Issue by ekmason** [Hyperobjekt/covid-19-behind-bars#485]
## Objective
Vaccine table on the homepage should display vaccination rates, instead of per 10K values (this will be the only spot on the site where rate is used over per 10k metric)

**Comment by Lane** [comment]
# Implementation Details

- [ ] revert column headings to "Vaccination Rate for `{GROUP}`"
- [ ] revert column formatter to use percent formatter instead of per 10k formatter.
