### ISSUE TITLE
Add Requested Fields to Netlify

### ISSUE THREAD

**Issue by ekmason** [Hyperobjekt/covid-19-behind-bars#486]
## Objective
As requested by the UCLA team, add fields in the CMS for the following: 
- [ ] State summary section copy
- [ ] View data here references (copy + link) 

## Details

For state summary section copy, please add the following fields (see snapshot):  
- Data grade: Descriptive text
- Data grade: View scorecard text 
- Summary section intro paragraph

![image.png](https://images.zenhubusercontent.com/605b8464e0e66f4aa2b43f51/9a9437e9-a7ef-44f5-9a5b-7683bd8fa5be)

**Comment by Lane** [comment]
# Implementation Tasks

- [ ] add `score_label`, `score_link_label`, `data_link`, `data_link_label` to the `aggregates` entry in the [state page language file](https://github.com/Hyperobjekt/covid-19-behind-bars/blob/development/content/lang/states.json)
- [ ] use the values from the state page language file in the [StateSummary section component](https://github.com/Hyperobjekt/covid-19-behind-bars/blob/development/src/components/states/sections/StateSummary.js)
- [ ] add a download button next to the data notes button in the StateSummary component that conditionally shows if `data_link`, `data_link_label` entries are populated in the state page language.  visually, this should look the same as it does on other sections / pages: 

![image.png](https://images.zenhubusercontent.com/5f99f2cab2fcd11a50e307b9/c2499aa4-8431-47dc-b939-224a1d91b800)

- [ ] update the [cms configuration for state language](https://github.com/Hyperobjekt/covid-19-behind-bars/blob/development/src/cms/lang/states.js) to include configuration for `score_label`, `score_link_label`, `data_link`, `data_link_label`
- [ ] test and confirm that updating the values via CMS works as intended
