### ISSUE TITLE
adjust center points and scale for state maps

### ISSUE THREAD

**Issue by Lane** [Hyperobjekt/covid-19-behind-bars#49]
some state maps are a bit off center, or could have increased zoom.

[edit the JSON](https://github.com/Hyperobjekt/covid-19-behind-bars/blob/production/packages/gatsby-ucla-site/src/common/data/us_state_centers.json) to set appropriate values

the width / height set  on the SVG in `FacilitiesMap` may also need to be adjusted to properly match aspect ratios of the states so that the state fills the available space accordingly

**Comment by james-minton** [comment]
Merged.
