### ISSUE TITLE
[DISCOVERY] Add Summary Table to ICE Page

### ISSUE THREAD

**Issue by ekmason** [Hyperobjekt/covid-19-behind-bars#500]
## Objective
Add summary table (same designs as state summary tables) to ICE page. 

## Outstanding Questions
- What will be the breakdown (columns and rows) be? Will the below be adequate? 
![image.png](https://images.zenhubusercontent.com/605b8464e0e66f4aa2b43f51/2529b384-0a91-4464-8bdc-da676232db3a)

## Workflow Checklist
- [x] [UCLA] Provide feature requirements
- [x] [HO] Draft feature specification
- [x] [UCLA] Approve feature specification
- [x] [HO] Mockup designs and plan of approach
- [x] [UCLA] Feedback round (feedback on how closely designs match agreed upon feature spec) 
- [x] [HO] Implement design feedback
- [x] [UCLA] Approve designs
- [x] [HO] Dev implementation demo (iterative) 
- [x] [UCLA] Provide feedback (on ways in which dev implementation differs from designs and agreed upon functionality) 
- [x] [HO] Final dev implementation demo
- [ ] [UCLA] Approve feature implementation for prod release

**Comment by lizdewolf** [comment]
That image is adequate! We don't have data for staff unfortunately, so only need one line. I might just want to think about if we say "detained people" instead

**Comment by ekmason** [comment]
Would the change to "detained people" occur across all state summary pages?

**Comment by Lane** [comment]
# Design TBD

- the ICE page has a different intro section design then our state / BOP pages.  should it be updated to match these pages, or should the aggregate section come after the ICE intro section?
- will there only be one row in this table (detained people)?  if so, having a wide table might not make sense and we might want to go with a different format

e.g.

# Nationwide Totals for Detained People

|   | Count  | Per 10k  |
| ------------ | ------------: | ------------: |
| Cumulative Cases  | 123,456  | 123  |
| Active Cases  | 1,234  | 12  |
| Deaths  | 123  | 2  |

**Comment by ekmason** [comment]
### Update from Liz (9.29)
We will move forward with the table view as opposed to the design to be used for topline stats on the homepage. For this page, we will add a summary table (same from BOP and state pages), with missing data for all staff (represented as `--`).

**Comment by Lane** [comment]
# Spec

- Add table to ICE page intro section

![image](https://user-images.githubusercontent.com/21034/136115977-d0f8feaf-e06d-4797-8b6b-346f4348889c.png)

# To be determined

- confirm which metrics to show (confirmed, active, deaths, tests)
- confirm if rates should be shown
- confirm source data location (is it the [latest_state_jurisdiction_counts](https://github.com/uclalawcovid19behindbars/data/blob/master/latest-data/latest_state_jurisdiction_counts.csv)?)
