### ISSUE TITLE
Add Map to BOP (Federal) Page

### ISSUE THREAD

**Issue by ekmason** [Hyperobjekt/covid-19-behind-bars#501]
## Objective
Add a map to the BOP page in order to make designs uniform to state and ICE pages

- This map will correlate to the facilities map on state pages
- Map will essentially be a replication of a filtered down homepage map (see screenshot below) 

![image.png](https://images.zenhubusercontent.com/605b8464e0e66f4aa2b43f51/4a986d45-bec2-4056-8177-28419de68196)

## Answered Questions
- Do we have the location data to correlated federal facilities to a map? Yes, we have lat/lon location data, no data to link to counties though. This could potentially be the homepage map (filtered down to Federal facilities) replicated. 
- Will we need a map next to the releases section as is the case with state pages? Since there are only 4 federal releases, this is will not be necessary. 
- Should we update the facilities table with a tooltip to view facility names? Yes, we will update the styling on the BOP facilities page to have a uniform tooltip to other areas in the site where facility name needs to be clarified/fully viewed. 

## Workflow Checklist
- [x] [UCLA] Provide feature requirements
- [x] [HO] Draft feature specification
- [x] [UCLA] Approve feature specification
- [x] [HO] Mockup designs and plan of approach
- [x] [UCLA] Feedback round (feedback on how closely designs match agreed upon feature spec) 
- [x] [HO] Implement design feedback
- [x] [UCLA] Approve designs
- [x] [HO] Dev implementation demo (iterative) 
- [x] [UCLA] Provide feedback (on ways in which dev implementation differs from designs and agreed upon functionality) 
- [ ] [HO] Final dev implementation demo
- [ ] [UCLA] Approve feature implementation for prod release

**Comment by lizdewolf** [comment]
Confirming that this map would be the image above. National with only federal facilities.

**Comment by Lane** [comment]
# Specification

- the federal page should have a map below the intro section table (#499)
- the map should follow the same visual style and functionality as the home page, with the following changes:
  - no jurisdiction filters (set to federal facilities by default)
  - spikes in the legend should correspond to federal facility color
- all content should be editable via CMS in the Language > Federal Page collection (section title, context paragraph, and notes)
