### ISSUE TITLE
State Specific Data Notes

### ISSUE THREAD

**Issue by ekmason** [Hyperobjekt/covid-19-behind-bars#525]
## Objective
Enable UCLA team to include data notes on state pages that are unique to a particular state. 
> Example: "Because Texas state data has been unreliable, we collect data from XYZ agency instead."

[Slack reference](https://hyperobjekt.slack.com/archives/C017SMGMFPU/p1630346825004500)

**Comment by Lane** [comment]
@ekmason do you know if this is for a specific section of the page (eg. aggregate summary, releases, etc.), or do they want the ability for all sections?

**Comment by ekmason** [comment]
@Lane the request was for the aggregate summary section, but I'll check to see if this functionality is needed for the grassroots and releases sections too.
