### ISSUE TITLE
Optimization

### ISSUE THREAD

**Issue by Lane** [Hyperobjekt/covid-19-behind-bars#81]
- [x] drop font loading for unused fonts (only need middle weight and bantam weight for Champion Gothic @james-minton )
- [ ] inject any styles needed to prevent flash of un-styled content
- [ ] check lighthouse for any red flags

**Comment by james-minton** [comment]
@Lane I have trimmed out the unused fonts. Just realizing there is an extra step here of moving fonts to "production," which may help with performance. I pulled this from the website: https://docs.google.com/document/d/1oPNo1Px2ShEVnBVo18qoZxdS14dmGG2nF_tthz9omRo/edit?usp=sharing

We might have to do this in parallel or I give someone the keys to the subscription.
