### ISSUE TITLE
Update decimals shown for rates 

### ISSUE THREAD

**Issue by erika-tyagi** [Hyperobjekt/covid-19-behind-bars#92]
**Is your feature request related to a problem? Please describe.**
This came up during our check-in meeting today – the goals are to (1) standardize the number of decimals we show in our rates across pages, and (2) make 0% rates more clear. 

**Describe the solution you'd like**
On both the homepage and state pages: 
* Round to the nearest whole number for all rates (e.g. "12%"). This is how the homepage is already set up, so I _think_ this would just require updating the state pages from 2 decimals to 0 decimals. 
* Display rates below 1% as "<1%" instead of 0%. This would need to be updated in both places. 

**Describe alternatives you've considered**
N/A 

**Additional context**
The motivation for the update is that we know our population data (the denominators in the rates) are unreliable, so we don't want to suggest more certainty in our rates by showing extra decimals. Feel free to reach out to me (tyagi@law.ucla.edu) or Liz (dewolf@law.ucla.edu) with any questions!

**Comment by hoshmn** [comment]
Minor detail: we could do either of the following for numbers < 1
- values in the range .5% - 1% appear as 1% (following the general rule of rounding to the nearest whole number), anything smaller appears as "< 0.5%", or
- _everything_ below 1% appears as "< 1%"
I'll go with the latter, which looks a little cleaner and matches the ticket's description, unless I hear dissent.

**Comment by erika-tyagi** [comment]
Just checked with Liz and that sounds great, thanks!
