### ISSUE TITLE
Immigration page

### ISSUE THREAD

**Issue by lizdewolf** [Hyperobjekt/covid-19-behind-bars#93]
Immigration-specific page: 

Audience: those interested specifically in immigration detention, rather than other carceral systems

- National map with ICE field office boundaries (UCLA has shape file)
- Shows location of facilities, number of cases and deaths within regional boundaries
- Simple table where the data is organized by field office region
- Visualizations by field office region

**Comment by laurendoone** [comment]
REQUIREMENTS:
- Look similar to homepage- national map with same styling
- Only includes ICE facilities
- Liz sent Josh a shape file with different boundaries for regions (ICE admin office regions)
- Can go directly to dev (no mockup needed)
