### ISSUE TITLE
Vaccine page

### ISSUE THREAD

**Issue by lizdewolf** [Hyperobjekt/covid-19-behind-bars#95]
A simple page that organizes media coverage about vaccine policies and distribution by state and by country. We don't need mapping or data visualization (at least not yet), since most of the data we have on this is anecdotal from media reports.

**Comment by james-minton** [comment]
Discussed in meeting: start simple, but maybe add ability to filter news by state/national going forward.

**Comment by laurendoone** [comment]
DESCOPED per Liz 2/1/21
